from os import getenv

TELEGRAM_BOT_TOKEN = getenv("TELEGRAM_BOT_TOKEN")

PHOTOS_MOUNT_POINT = getenv("PHOTOS_MOUNT_POINT")
FACES_MOUNT_POINT = getenv("FACES_MOUNT_POINT")

TELEGRAM_API_HOST = "https://api.telegram.org"
TELEGRAM_API_URL = f"{TELEGRAM_API_HOST}/bot{TELEGRAM_BOT_TOKEN}"
